### PR TITLE
Fix Lego.cs 

### PR DESCRIPTION
**Pull request by th3raid0r**
Issues with existing version included:

1. Incorrect image paths (unless folder is renamed)
2. Some buttons mapped incorrectly (assuming hhd daemon implementation)
3. RB and LB were HUGE in the UI, brought the scaling way down. 

This PR should fix them all.

### CODE REVIEW

**Comment by frazse** [comment]
on number 3, could you show where the scaling is way too big? on my legion go .36 is way too small :s

**Comment by th3raid0r** [comment]
@frazse - I just noticed that last night. So there are two areas where those buttons are displayed. 

1. The Controller screen - where all controls are layed out, ideally with equal scaling. This is now too small, I agree.
2. When selecting an element with LB/RB navigation, the glyphs flank the items which those controls navigate through. When set to 88, these glyphs are massive and actually increase the vertical needed space for the navigational element.

I'll get a screenshot shortly.

**Comment by th3raid0r** [comment]
Here's the element I'm describing at 88:
Screenshot-88

**Comment by th3raid0r** [comment]
And here it is at 36:
screenshot-36

**Pull request merged**
